### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by AlmiS** [transceptor-technology/siridb-http#12]
Is it possible to make siridb-http work with IPv6? The configuration file does not seem to provide this option.

**Comment by joente** [comment]
Thanks for reporting this issue. Both SiriDB (`siridb-server`) and `siridb-admin` are already IPv6 compatible and my guess is that implementing IPv6 for `siridb-http` will be not that hard.

**Comment by joente** [comment]
Release version 1.0.7 with IPv6 support: https://github.com/transceptor-technology/siridb-http/releases/tag/1.0.7

We had to implement two changes:
 - SiriDB HTTP did not listen to IPv6 because we were listening to `0.0.0.0`. By removing this binding the server starts listening to both IPv4 and IPv6.
- SiriDB HTTP has a config where the SiriDB servers are configured. This config field will be transformed into a list with hostname/port combinations. The translation from the string to this list simply didn't understand the IPv6 syntax. Implemented a function `get_hostlist()` which does the translation including IPv6 addresses.

Valid examples for the `servers` variable in the configuration file:
```
# multiple servers are allowed and should be comma separated
servers = siridb01.local,siridb02.local,siridb03.local,siridb04.local

# IPv4 is allowed
servers = 10.20.30.40

# IPv6 is allowed
servers = 2001:0db8:85a3:0000:0000:8a2e:0370:7334

# The address part must be wrapped in square brackets in case an alternative port is required
servers = [::1]:5050
```
